### ISSUE TITLE
 Confirm space for 100 attendees

### ISSUE THREAD

**Issue by shepazu** [w3c/blockchain#1]
There's been considerable interest in the blockchain workshop, and we may need more than 60 slots for attendees. Ideally, we would have room for 100 attendees seated at round tables, with 5–6 chairs per table (so nobody has to sit facing away from the stage). That's 17-20 tables.

We need to confirm that:

1) the venue has room for 17-20 round tables and a stage
2) we have enough tables and chairs (17-20 round tables, 100+ chairs) without having to rent more.

**Comment by dazzaji** [comment]
I'll check into it.

**Comment by dazzaji** [comment]
Should have a more definite reply on this inquiry in the next day or two.

**Comment by dazzaji** [comment]
The answer is yes.  An implication is that we'll need to rent some additional tables for the event.
