### ISSUE TITLE
Demo Area?

### ISSUE THREAD

**Issue by shepazu** [w3c/blockchain#2]
Some people have asked for a demo area, outside the workshop room. I know we reserved the lobby area, but I also know there's another meeting going on adjacent to that, and we need to avoid disturbing them. Is there somewhere to the side that would be suitable?

For each demo presenter, we would need:
- a table (about 6ft x 3ft)
- a monitor 
- electricity

**Comment by dazzaji** [comment]
Probably the open space outside the Multipurpose Room.  

I'll check into it.

**Comment by dazzaji** [comment]
This is a common use of the space.  Just tracking down the details and figuring out the logistics of putting in "work orders" for this setup.

**Comment by dazzaji** [comment]
We have the demo area secured.  Issue resolved.
