### ISSUE TITLE
github repo conflict with blockchain CG and blockchain Workshop

### ISSUE THREAD

**Issue by mountielee** [w3c/blockchain#8]
I know workshop is onetime event.
current github repo "blockchain" is used for blockchainCG and blockchainWorkshop both.
do we need to divide activities into different branches?

**Comment by shepazu** [comment]
There may be more blockchain workshops or events, and it's even possible that there could be some official blockchain standardization activity in the future, in addition to the informal Blockchain CG.

Personally, I think it's more useful at this point to have all the blockchain stuff share the same repo, so people outside W3C can easily find what we're doing on the topic. But if you want to create a separate repo for the Blockchain CG, that's also okay.

**Comment by dprophet** [comment]
> more useful at this point to have all the blockchain stuff share the same repo

Agreed. Dont split into different repo's. Dont put on different branches because this causes more problems with finding the right content.

Different directories for event material but shared directories for major themes like use cases, capabilities, features, etc.

**Comment by dazzaji** [comment]
evidently, the w3c has resolved this based upon demonstrable choices with repo setup.  therefor i am closing this issue so it does not show up as active and we can focus on actions to be taken.
